trigger:
  branches:
    include:
      - main # run on main before build
      # trigger for merge queue branches
      - gh-readonly-queue/*

pr:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.23.0

variables:
  - name: projects
    value: address-lookup,notify,pins-components

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    skipAzureAuth: true
    skipGitTagging: true
    validationJobs:
      - name: Format
        steps:
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm ci
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run format-check
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run lint
      - ${{each project in split(variables.projects, ',')}}:
          - name: ${{ project }} Tests
            steps:
              - template: ../steps/node_script.yml
                parameters:
                  nodeVersion: 22
                  script: npm ci
                  workingDirectory: $(Build.Repository.LocalPath)/services/${{ project }}
              - template: ../steps/node_script.yml
                parameters:
                  nodeVersion: 22
                  script: npm run test
                  workingDirectory: $(Build.Repository.LocalPath)/services/${{ project }}
