# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
      - services/pdf/*

variables:
  tag: '$(Build.BuildId)'
  pdfServiceDockerfilePath: '$(Build.SourcesDirectory)/services/pdf/Dockerfile'
  imageRepository: 'planninginspectorateappealplanningdecision'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build_PDF_API
    displayName: Build PDF Service
    # Change for dependency
    dependsOn: BuildCommonsImage 
    jobs:
      - job: BuildApiServiceImage
        displayName: Build Api Service Image
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(pdfServiceDockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)-pdf-service-image

